-- MySQL Script generated by MySQL Workbench
-- Tue Jul 20 14:24:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema admin_panel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema admin_panel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admin_panel` DEFAULT CHARACTER SET utf8 COLLATE utf8_slovenian_ci ;
USE `admin_panel` ;

-- -----------------------------------------------------
-- Table `admin_panel`.`admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_panel`.`admin_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
